import { useRef, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, Check, ChevronRight, Compass, GraduationCap, Target, UserRound } from 'lucide-react';
import type { StudentProfile, UniversityRecommendedCareer, UniversitySourcesAnalysisResponse } from '@/types';
import { useAppQuery } from '@/hooks/useAppQuery';
import { psychometricService } from '@/services/psychometricService';
import { ProgressRing } from '@/components/student/dashboard/StudentDashboard';
import { RecommendedCareerCard } from '@/components/student/career/RecommendedCareerCard';
import '../career/career-explorer.css';
import './ai-guidance.css';

type Qualification = { programmeName: string; university: string; qualifies: boolean | null; qualificationMessage: string; admissionRequirements: string[]; missingRequirements: string[]; weakSubjects: string[]; improvementSuggestions: string[]; alternatives: string[] };
type Props = { profile?: StudentProfile; advice?: UniversitySourcesAnalysisResponse; careers: UniversityRecommendedCareer[]; qualifications: Qualification[]; premium: boolean; controls: ReactNode; details: ReactNode; loading: boolean; error?: string | null };
function Card({ title, children, icon = 'compass' }: { title: string; children: ReactNode; icon?: 'compass' | 'book' | 'target' }) { const Icon = icon === 'book' ? BookOpen : icon === 'target' ? Target : Compass; return <section className="ed-panel ag-card"><header><Icon/><h2>{title}</h2></header>{children}</section>; }
const List = ({ items }: { items: string[] }) => <ul className="ag-list">{items.map((item,index) => <li key={`${item}-${index}`}>{item}</li>)}</ul>;
export function AiGuidance({ profile, advice, careers, qualifications, premium, controls, details, loading, error }: Props) {
 const psychometric = useAppQuery({ queryKey: ['student-psychometric-latest'], queryFn: psychometricService.latestStudent });
 const detail = useRef<HTMLDetailsElement>(null);
 const openDetails = () => { if(detail.current){ detail.current.open=true; detail.current.scrollIntoView({behavior:'smooth',block:'start'}); } };
 const factors = [
  { label:'Profile information', complete:Boolean(profile?.firstName && profile?.lastName), to:'/student/profile' },
  { label:'Academic results', complete:Boolean(profile?.subjectAchievements?.some(item=>item.subjectName && item.achievementLevel)), to:'/student/profile?tab=academic' },
  { label:'Interests', complete:Boolean(profile?.interests?.length), to:'/student/profile?tab=interests' },
  { label:'Skills', complete:Boolean(profile?.skills?.length), to:'/student/profile?tab=interests' },
  { label:'Career goals', complete:Boolean(profile?.careerGoals?.trim()), to:'/student/profile?tab=goals' },
  { label:'Psychometric assessment', complete:Boolean(psychometric.data?.id), to:'/student/psychometric' },
 ];
 const actions = premium ? advice?.recommendedNextSteps ?? [] : [];
 const improvements = [...new Set(qualifications.flatMap(item=>item.improvementSuggestions))];
 return <div className="ec-explorer ag-guidance">
  <div className="ag-top"><section className="ed-panel ag-hero"><span className="ag-eyebrow">AI GUIDANCE</span><h1>Your Future.<br/><em>Guided by Your Profile.</em></h1><p>Get personalised career, university and study guidance based on your academic results, interests, strengths and goals.</p><div className="ec-controls">{controls}</div><small>Fast: quick personalised guidance. Deep: more comprehensive analysis.</small>{loading && <p role="status" className="ag-status">Reviewing your profile and available university information...</p>}{error && <p role="alert" className="ec-error">{error}</p>}</section>
  <Card title="Guidance Readiness" icon="target"><div className="ag-readiness"><div><ProgressRing value={profile?.profileCompleteness ?? null}/><small>Profile completion</small></div><ul>{factors.map(item=><li key={item.label}><span className={`ed-check ${item.complete?'is-complete':''}`}>{item.complete && <Check size={10}/>}</span><Link to={item.to}>{item.label}</Link></li>)}</ul></div><p className="ec-note">Completion is supplied by your profile. It is not an admission or career-match score.</p>{psychometric.isError && <p className="ec-note">Assessment status is temporarily unavailable.</p>}</Card></div>
  <div className="ag-columns"><div className="ag-main">
   {!advice && <Card title="How EduRite Guidance Works"><div className="ag-how">{['Profile','Academic Results','Interests & Strengths','AI Analysis','Career & Study Guidance'].map((label,index)=><div key={label}><span>{index+1}</span><strong>{label}</strong>{index<4 && <ChevronRight size={15}/>}</div>)}</div><p className="ec-note">Review your profile, choose a guidance mode, then generate recommendations. Your results and source information will appear here.</p><Link className="ag-link" to="/student/profile">Review My Profile <ChevronRight size={14}/></Link></Card>}
   {advice && <Card title="Personalised Insights"><div className="ag-insights">{careers[0] && <article><Compass/><h3>Career Direction</h3><p>{careers[0].recommendationReason || careers[0].reason}</p></article>}{advice.suitabilityScoreReason && <article><Target/><h3>Profile Suitability</h3><p>{advice.suitabilityScoreReason}</p></article>}{premium && Boolean(advice.skillGaps?.length) && <article><BookOpen/><h3>Areas to Improve</h3><List items={advice.skillGaps}/></article>}{premium && advice.summary && <article><GraduationCap/><h3>Study Direction</h3><p>{advice.summary}</p></article>}</div>{advice.warningMessage && <p className="ec-error">{advice.warningMessage}</p>}{advice.status==='PARTIAL' && <p className="ag-status">Some sources were unavailable. Review the source details before making study decisions.</p>}</Card>}
   {Boolean(careers.length) && <Card title="Recommended Careers"><div className="ec-career-cards">{careers.map((item,index)=><RecommendedCareerCard key={item.name} item={item} index={index} onDetails={openDetails}/>)}</div><Link className="ag-link" to="/student/career-roadmaps">Explore Career Roadmaps <ChevronRight size={14}/></Link></Card>}
   {premium && Boolean(qualifications.length) && <Card title="Recommended Study Options" icon="book"><div className="ag-qualifications">{qualifications.map((item,index)=><article key={`${item.programmeName}-${index}`}><div className="ag-qualification-heading"><GraduationCap/><div><h3>{item.programmeName}</h3><p>{item.university}</p></div></div><span className={`ag-badge ${item.qualifies===false?'ag-needs-work':''}`}>{item.qualifies===null?'Needs Manual Verification':item.qualifies?'Parsed Subject Requirements Met':'Subject Requirements Not Met'}</span><p className="ec-note">{item.qualificationMessage} Final admission remains subject to institution verification.</p><details><summary>Qualification Readiness / View Details</summary><h4>Your Profile</h4><p>{profile?.selectedGrade || 'Grade not added'} · {profile?.qualificationLevel || 'Qualification level not added'}</p><List items={(profile?.subjectAchievements??[]).map(subject=>`${subject.subjectName}: ${subject.achievementLevel ? `Level ${subject.achievementLevel}`:'Level not added'}`)}/><h4>Requirements</h4>{item.admissionRequirements.length?<List items={item.admissionRequirements}/>:<p>Requirements need manual verification.</p>}{Boolean(item.missingRequirements.length+item.weakSubjects.length)&&<><h4>Missing / Unmet Requirements</h4><List items={[...item.missingRequirements,...item.weakSubjects]}/></>}{Boolean(item.improvementSuggestions.length)&&<><h4>Suggested Actions</h4><List items={item.improvementSuggestions}/></>}{Boolean(item.alternatives.length)&&<><h4>Suggested Alternatives</h4><List items={item.alternatives}/></>}<button className="ag-link" onClick={openDetails}>Review full guidance &amp; verification warnings <ChevronRight size={14}/></button></details></article>)}</div><Link className="ag-link" to="/student/universities">Explore Universities <ChevronRight size={14}/></Link></Card>}
   {advice && !premium && <Card title="Study Guidance" icon="book"><p className="ec-note">Detailed programme analysis and expanded guidance require Premium.</p><Link className="ag-link" to="/student/subscription">View subscription options <ChevronRight size={14}/></Link><Link className="ag-link" to="/student/universities">Explore Universities <ChevronRight size={14}/></Link></Card>}
  </div><aside className="ag-aside"><Card title="Your Action Plan" icon="target">{actions.length?<ol className="ag-plan">{actions.map((item,index)=><li key={`${item}-${index}`}><span>{index+1}</span><p>{item}</p></li>)}</ol>:<p className="ec-empty">{advice?'No personalised action steps are available in this response. Review the relevant profile actions below.':'Generate guidance to see your personalised next steps.'}</p>}<Link className="ag-link" to="/student/career-roadmaps">Career Roadmaps <ChevronRight size={14}/></Link></Card>
  <Card title="Improve Your Chances">{factors.filter(item=>!item.complete).map(item=><Link className="ag-action" key={item.label} to={item.to}><UserRound size={17}/><span>{item.label==='Psychometric assessment'?'Review assessment':`Complete ${item.label.toLowerCase()}`}</span><ChevronRight size={14}/></Link>)}{!profile?.transcriptFileUrl && <Link className="ag-action" to="/student/profile?tab=settings"><BookOpen size={17}/><span>Upload your transcript</span><ChevronRight size={14}/></Link>}{improvements.map(item=><Link className="ag-action" key={item} to="/student/profile?tab=academic"><BookOpen size={17}/><span>{item}</span><ChevronRight size={14}/></Link>)}{factors.every(item=>item.complete)&&profile?.transcriptFileUrl&&!improvements.length&&<p className="ec-empty">Your profile sections are complete. Review your guidance for programme-specific next steps.</p>}</Card></aside></div>
  {advice && <details ref={detail} className="ed-panel ec-details"><summary>Full guidance, career details, requirements &amp; sources</summary>{details}</details>}
 </div>;
}
