ALTER TABLE subscriptions
    ADD COLUMN IF NOT EXISTS trial_start_date TIMESTAMP WITH TIME ZONE;

ALTER TABLE subscriptions
    ADD COLUMN IF NOT EXISTS trial_end_date TIMESTAMP WITH TIME ZONE;

ALTER TABLE subscriptions
    ADD COLUMN IF NOT EXISTS premium_until TIMESTAMP WITH TIME ZONE;

ALTER TABLE subscriptions
    ADD COLUMN IF NOT EXISTS trial_used BOOLEAN NOT NULL DEFAULT FALSE;
