-- Existing subscriptions and payments are preserved. No historical migration is changed.
CREATE TABLE student_ai_usage (
 id UUID PRIMARY KEY, user_id UUID NOT NULL REFERENCES users(id), period_start DATE NOT NULL,
 status VARCHAR(16) NOT NULL CHECK (status IN ('RESERVED','SUCCEEDED','FAILED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX student_ai_usage_period_idx ON student_ai_usage(user_id,period_start,status);
INSERT INTO pricing_plans(id,code,name,description,currency,amount,billing_interval,features,active,premium,display_order,created_at,updated_at) VALUES (gen_random_uuid(),'PLAN_BASIC','Basic','Start discovering what your future could look like.','ZAR',0,'MONTHLY','["Create learner profile", "Explore basic career information", "Limited career profiles (5 results per search)", "Basic APS calculator", "Limited course and institution search (5 results per search)", "Browse bursaries and scholarships", "Basic progress tracking", "Limited learning resources (5 results per search)", "5 AI interactions per month"]'::jsonb,true,false,0,now(),now()) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,currency=EXCLUDED.currency,amount=EXCLUDED.amount,billing_interval=EXCLUDED.billing_interval,features=EXCLUDED.features,active=true,premium=EXCLUDED.premium,display_order=EXCLUDED.display_order;
INSERT INTO pricing_plans(id,code,name,description,currency,amount,billing_interval,features,active,premium,display_order,created_at,updated_at) VALUES (gen_random_uuid(),'PLAN_PREMIUM','Premium','Understand your options and create a clear pathway for your future.','ZAR',59,'MONTHLY','["Everything in Basic", "Full career assessment", "Personalised career recommendations", "Subject-to-career matching", "Full APS calculator and progress tracking", "Explore universities and TVET colleges", "Full access to bursaries and scholarships", "Save opportunities", "Personalised career roadmap", "Full learning resources", "30 AI interactions per month", "Study option recommendations", "Progress dashboard"]'::jsonb,true,true,1,now(),now()) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,currency=EXCLUDED.currency,amount=EXCLUDED.amount,billing_interval=EXCLUDED.billing_interval,features=EXCLUDED.features,active=true,premium=EXCLUDED.premium,display_order=EXCLUDED.display_order;
INSERT INTO pricing_plans(id,code,name,description,currency,amount,billing_interval,features,active,premium,display_order,created_at,updated_at) VALUES (gen_random_uuid(),'PLAN_PREMIUM_YEARLY','Premium','Understand your options and create a clear pathway for your future.','ZAR',599,'YEARLY','["Everything in Basic", "Full career assessment", "Personalised career recommendations", "Subject-to-career matching", "Full APS calculator and progress tracking", "Explore universities and TVET colleges", "Full access to bursaries and scholarships", "Save opportunities", "Personalised career roadmap", "Full learning resources", "30 AI interactions per month", "Study option recommendations", "Progress dashboard"]'::jsonb,true,true,2,now(),now()) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,currency=EXCLUDED.currency,amount=EXCLUDED.amount,billing_interval=EXCLUDED.billing_interval,features=EXCLUDED.features,active=true,premium=EXCLUDED.premium,display_order=EXCLUDED.display_order;
INSERT INTO pricing_plans(id,code,name,description,currency,amount,billing_interval,features,active,premium,display_order,created_at,updated_at) VALUES (gen_random_uuid(),'PLAN_PRO','Pro','Get deeper guidance and support to turn your pathway into action.','ZAR',119,'MONTHLY','["Everything in Premium", "Advanced career and qualification matching", "Priority bursary and opportunity matching", "Advanced personalised career roadmap", "Detailed academic analysis and improvement plan", "AI opportunity assistant: applications, essays and CV assistance", "Application preparation and guidance", "100 AI interactions per month", "Advanced progress dashboard and insights", "Early access to new features", "Parent / guardian insights when available"]'::jsonb,true,true,3,now(),now()) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,currency=EXCLUDED.currency,amount=EXCLUDED.amount,billing_interval=EXCLUDED.billing_interval,features=EXCLUDED.features,active=true,premium=EXCLUDED.premium,display_order=EXCLUDED.display_order;
INSERT INTO pricing_plans(id,code,name,description,currency,amount,billing_interval,features,active,premium,display_order,created_at,updated_at) VALUES (gen_random_uuid(),'PLAN_PRO_YEARLY','Pro','Get deeper guidance and support to turn your pathway into action.','ZAR',1199,'YEARLY','["Everything in Premium", "Advanced career and qualification matching", "Priority bursary and opportunity matching", "Advanced personalised career roadmap", "Detailed academic analysis and improvement plan", "AI opportunity assistant: applications, essays and CV assistance", "Application preparation and guidance", "100 AI interactions per month", "Advanced progress dashboard and insights", "Early access to new features", "Parent / guardian insights when available"]'::jsonb,true,true,4,now(),now()) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,currency=EXCLUDED.currency,amount=EXCLUDED.amount,billing_interval=EXCLUDED.billing_interval,features=EXCLUDED.features,active=true,premium=EXCLUDED.premium,display_order=EXCLUDED.display_order;
