-- Extend the existing curriculum catalogue; preserve existing subjects and learner data.
-- Source: DBE CAPS FET subject catalogue (education.gov.za).
INSERT INTO subject_catalogue (name, phase, grade_range, subject_type, language_level, is_language)
SELECT v.* FROM (VALUES
('Afrikaans', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Afrikaans', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('English', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('English', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('isiNdebele', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('isiNdebele', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('isiXhosa', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('isiXhosa', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('isiZulu', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('isiZulu', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Sepedi', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Sepedi', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Sesotho', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Sesotho', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Setswana', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Setswana', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('siSwati', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('siSwati', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Tshivenda', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Tshivenda', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Xitsonga', 'Senior', 'Grades 7-9', 'Language', 'Home Language', TRUE),
('Xitsonga', 'Senior', 'Grades 7-9', 'Language', 'First Additional Language', TRUE),
('Afrikaans', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Afrikaans', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Afrikaans', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('English', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('English', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('English', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('isiNdebele', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('isiNdebele', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('isiNdebele', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('isiXhosa', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('isiXhosa', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('isiXhosa', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('isiZulu', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('isiZulu', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('isiZulu', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Sepedi', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Sepedi', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Sepedi', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Sesotho', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Sesotho', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Sesotho', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Setswana', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Setswana', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Setswana', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('siSwati', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('siSwati', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('siSwati', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Tshivenda', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Tshivenda', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Tshivenda', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Xitsonga', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('Xitsonga', 'FET', 'Grades 10-12', 'Language', 'First Additional Language', TRUE),
('Xitsonga', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('South African Sign Language', 'FET', 'Grades 10-12', 'Language', 'Home Language', TRUE),
('French', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Mandarin', 'FET', 'Grades 10-12', 'Language', 'Second Additional Language', TRUE),
('Technical Mathematics', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Technical Sciences', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Marine Sciences', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Maritime Economics', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Nautical Science', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Equine Studies', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE),
('Sport and Exercise Science', 'FET', 'Grades 10-12', 'Elective', NULL, FALSE)
) AS v(name, phase, grade_range, subject_type, language_level, is_language)
WHERE NOT EXISTS (SELECT 1 FROM subject_catalogue s WHERE lower(s.name)=lower(v.name) AND s.phase=v.phase AND s.language_level IS NOT DISTINCT FROM v.language_level);
