import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { BookOpen, Building2, Wallet } from 'lucide-react';
import { useAppQuery } from '@/hooks/useAppQuery';
import { institutionService } from '@/services/institutionService';
import { courseService } from '@/services/courseService';
import { universityInfoService } from '@/services/universityInfoService';
import { studentService } from '@/services/studentService';
import { bursaryService } from '@/services/bursaryService';
import { jobsService } from '@/services/jobsService';
import { createInstitutionSlug } from '@/lib/institutionSlug';
import { buildMergedInstitutionList, resolveInstitutionDisplay } from '@/lib/institutionRegistry';
import type { Institution, UnifiedOpportunity } from '@/types';
import { ExploreDialog } from './ExploreDialog';
export const safeWeb = (value?: string | null) => { try {const url=new URL(value??'');return ['https:','http:'].includes(url.protocol)?url.href:undefined;}catch{return undefined;} };
export const itemsOf = <T,>(data?: T[] | {content:T[]}) => Array.isArray(data)?data:data?.content??[];
export function QueryState({ loading, error, empty }: {loading:boolean;error:boolean;empty?:boolean}) {return loading?<div className="ex-skeleton" role="status">Loading current information...</div>:error?<p className="ec-error" role="alert">This information is temporarily unavailable. Please try again.</p>:empty?<p className="ec-empty">No results available. Try a broader search or another category.</p>:null;}

function InstitutionDetails({ institution }: { institution: Institution }) {
 const resolved=resolveInstitutionDisplay(institution),slug=createInstitutionSlug(resolved.displayName);
 const courses=useAppQuery({queryKey:['explore-institution-programmes',slug],queryFn:()=>universityInfoService.programmes(slug)});
 const requirements=useAppQuery({queryKey:['explore-institution-requirements',slug],queryFn:()=>universityInfoService.admissionRequirements(slug)});
 return <><p>{resolved.description}</p><p className="ec-note">{[resolved.city,resolved.province,resolved.institutionType].filter(Boolean).join(' · ')}</p>{safeWeb(resolved.officialWebsite || resolved.website)&&<a className="ex-link" href={safeWeb(resolved.officialWebsite || resolved.website)} target="_blank" rel="noreferrer">Official institution website</a>}<h3>Programmes</h3><QueryState loading={courses.isLoading} error={courses.isError}/>{courses.data?.programmes?.map(item=><article className="ex-result" key={item.id}><h4>{item.name}</h4><p>{[item.duration,item.studyMode,item.campus].filter(Boolean).join(' · ')}</p><small>{item.retrievalStatus}</small>{safeWeb(item.programmeUrl)&&<a href={safeWeb(item.programmeUrl)} target="_blank" rel="noreferrer">Official programme information</a>}</article>)}<h3>Admission requirements</h3><QueryState loading={requirements.isLoading} error={requirements.isError}/>{requirements.data?.requirements?.map(item=><article className="ex-result" key={item.id}><h4>{item.programmeName||item.requirementTitle}</h4>{item.apsMinimum!=null&&<p>APS: {item.apsMinimum}</p>}<p>{[...item.requiredSubjects,...item.minimumMarks,item.nscRequirement,item.languageRequirement,item.facultySpecificRequirement,item.additionalTests].filter(Boolean).join(' · ')}</p>{safeWeb(item.sourceUrl)&&<a href={safeWeb(item.sourceUrl)} target="_blank" rel="noreferrer">Verify requirements</a>}</article>)}<p className="ec-note">Requirements are not a guarantee of admission. Verify with the institution before applying.</p></>;
}
export function ExploreInstitutions({query}:{query:string}) {
 const [params, setParams] = useSearchParams();
 const data=useAppQuery<Institution[]>({queryKey:['student','institutions'],queryFn:()=>institutionService.list()});
 const [province,setProvince]=useState(''),[type,setType]=useState(''),[faculty,setFaculty]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState<Institution|null>(null);
 const all=buildMergedInstitutionList(data.data??[], () => true).map(item=>resolveInstitutionDisplay(item));
 const institutionSlug = params.get('institution');
 useEffect(() => { if (institutionSlug) { const match = all.find(item => createInstitutionSlug(item.displayName) === institutionSlug); if (match) setSelected(match as Institution); } }, [institutionSlug, data.data]);
 const options=(key:'province'|'institutionType')=>[...new Set(all.map(item=>item[key]).filter(Boolean))];
 const filtered=all.filter(item=>(!query||[item.displayName,item.abbreviation,item.province,item.city].join(' ').toLowerCase().includes(query.toLowerCase()))&&(!province||item.province===province)&&(!type||item.institutionType===type)&&(!faculty||item.faculties?.includes(faculty))&&(!status||item.applicationStatus===status));
 return <section className="ed-panel"><header><Building2/><h2>Institutions</h2></header><div className="ex-filters"><select aria-label="Institution province" value={province} onChange={e=>setProvince(e.target.value)}><option value="">All provinces</option>{options('province').map(item=><option key={item}>{item}</option>)}</select><select aria-label="Institution type" value={type} onChange={e=>setType(e.target.value)}><option value="">All institution types</option>{options('institutionType').map(item=><option key={item}>{item}</option>)}</select><select aria-label="Faculty" value={faculty} onChange={e=>setFaculty(e.target.value)}><option value="">All faculties</option>{[...new Set(all.flatMap(item=>item.faculties??[]))].map(item=><option key={item}>{item}</option>)}</select><select aria-label="Application status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All application statuses</option>{['OPEN','OPENING_SOON','CLOSED'].map(item=><option key={item}>{item}</option>)}</select></div><QueryState loading={data.isLoading} error={data.isError} empty={!filtered.length}/><div className="ex-results">{filtered.map(item=><article className="ex-result" key={item.id||item.displayName}><h3>{item.displayName}</h3><p>{[item.province,item.institutionType].filter(Boolean).join(' · ')}</p>{item.applicationStatus&&<small>{item.applicationStatus}</small>}<button onClick={()=>setSelected(item as Institution)}>Courses &amp; requirements</button></article>)}</div>{selected&&<ExploreDialog title={selected.name} onClose={()=>{setSelected(null);setParams(previous=>{const next=new URLSearchParams(previous);next.delete('institution');return next;},{replace:true});}}><InstitutionDetails institution={selected}/></ExploreDialog>}</section>;
}
export function ExploreCourses({query}:{query:string}) {
 const courses=useAppQuery({queryKey:['explore-courses',query],queryFn:()=>courseService.list({q:query,size:100})});
 const [level,setLevel]=useState('');const items=itemsOf(courses.data);const filtered=items.filter(item=>(!query||`${item.name} ${item.institutionName}`.toLowerCase().includes(query.toLowerCase()))&&(!level||item.level===level));
 return <section className="ed-panel"><header><BookOpen/><h2>Courses &amp; Qualifications</h2></header><select aria-label="Qualification level" value={level} onChange={e=>setLevel(e.target.value)}><option value="">All qualification levels</option>{[...new Set(items.map(item=>item.level).filter(Boolean))].map(item=><option key={item}>{item}</option>)}</select><QueryState loading={courses.isLoading} error={courses.isError} empty={!filtered.length}/><div className="ex-results">{filtered.map(item=><article className="ex-result" key={item.id}><h3>{item.name}</h3><p>{item.institutionName}</p><p>{[item.duration,item.level].filter(Boolean).join(' · ')}</p><details><summary>View Details</summary><p>{item.name} at {item.institutionName}</p><p>Duration: {item.duration||'Not supplied'}</p><p>Use Institutions to review official programme admission requirements.</p></details></article>)}</div></section>;
}
export function ExploreFunding({query='',compact=false,onViewAll}:{query?:string;compact?:boolean;onViewAll?:()=>void}) {
 const data=useAppQuery({queryKey:['explore-funding',query],queryFn:()=>query?bursaryService.search({q:query}).then(result=>result.items):bursaryService.recommended()});
 return <section className="ed-panel ec-funding"><header><Wallet/><div><h2>Bursaries &amp; Funding</h2><p>{query?'Funding search results':'Recommended funding opportunities'}</p></div>{onViewAll&&<button onClick={onViewAll}>View All</button>}</header><QueryState loading={data.isLoading} error={data.isError} empty={!data.data?.length}/>{(compact?data.data?.slice(0,3):data.data)?.map(item=><article className="ex-fund" key={item.externalId}><h3>{item.title}</h3><small>{item.provider}</small>{item.deadline&&<small>Deadline: {item.deadline}</small>}<details><summary>View Details</summary><p>{[item.eligibility,item.qualificationLevel,item.region].filter(Boolean).join(' · ')||'Check the provider for full eligibility requirements.'}</p>{safeWeb(item.applicationLink)&&<a href={safeWeb(item.applicationLink)} target="_blank" rel="noreferrer">Open provider application</a>}</details></article>)}</section>;
}
export function ExploreOpportunities({query,career}:{query:string;career:string}) {
 const qc=useQueryClient();const [type,setType]=useState('ALL'),[detail,setDetail]=useState<UnifiedOpportunity|null>(null);
 const data=useAppQuery({queryKey:['student-opportunities','explore',query,type],queryFn:()=>studentService.searchOpportunities({q:query,opportunityType:type})});
 const jobs=useAppQuery({queryKey:['explore-jobs',query,career],queryFn:()=>jobsService.search({query:query||career,location:''}),enabled:Boolean(query||career)});
 const save=useMutation({mutationFn:(item:UnifiedOpportunity)=>item.saved?studentService.unsaveOpportunity(item.type,item.id):studentService.saveOpportunity(item.type,item.id,item.title),onSuccess:()=>qc.invalidateQueries({queryKey:['student-opportunities']})});
 return <section className="ed-panel"><header><Wallet/><h2>Opportunities For You</h2></header><div className="ex-filters"><select aria-label="Opportunity type" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All opportunities</option><option value="CAREER">Careers</option><option value="JOB">Jobs</option></select></div><QueryState loading={data.isLoading} error={data.isError} empty={!data.data?.length}/>{save.isError&&<p role="alert" className="ec-error">Could not update the saved opportunity. Please try again.</p>}<div className="ex-results">{data.data?.map(item=><article className="ex-result" key={`${item.type}-${item.id}`}><h3>{item.title}</h3><p>{[item.type,item.industry,item.location,item.qualification].filter(Boolean).join(' · ')}</p><div className="ex-actions"><button disabled={save.isPending} onClick={()=>save.mutate(item)}>{item.saved?'Unsave':'Save'}</button><button onClick={()=>setDetail(item)}>View Details</button></div></article>)}</div>{Boolean(query||career)&&<><h3 className="ex-subheading">Related job opportunities</h3><QueryState loading={jobs.isLoading} error={jobs.isError} empty={!jobs.data?.length}/><div className="ex-results">{jobs.data?.map(item=><article className="ex-result" key={item.id}><h3>{item.title}</h3><p>{item.company} · {item.location}</p><small>{item.contractType||item.category}</small><details><summary>View Details</summary><p>{item.description}</p>{safeWeb(item.redirectUrl)&&<a href={safeWeb(item.redirectUrl)} target="_blank" rel="noreferrer">View application</a>}</details></article>)}</div></>}{detail&&<ExploreDialog title={detail.title} onClose={()=>setDetail(null)}><p>{[detail.field,detail.industry,detail.location,detail.qualification,detail.demand].filter(Boolean).join(' · ')}</p><button onClick={()=>{save.mutate(detail);setDetail(null);}}>{detail.saved?'Unsave opportunity':'Save opportunity'}</button></ExploreDialog>}</section>;
}
